[package]
name = "microcicd"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
serde = { version = "1", features = ["derive"] }
serde_derive = "1.0"
once_cell = "1.10"